{% set name = "asciidoc" %}
{% set version = "10.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asciidoc-{{ version }}.tar.gz
  sha256: d9f13c285981b3c7eb660d02ca0a2779981e88d48105de81bb40445e60dddb83

build:
  noarch: python
  entry_points:
    - asciidoc=asciidoc.asciidoc:cli
    - a2x=asciidoc.a2x:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - asciidoc
  commands:
    - pip check
    - asciidoc --help
    - a2x --help
  requires:
    - pip

about:
  home: https://asciidoc.org
  doc_url: http://asciidoc.org/userguide.html
  dev_url: https://github.com/asciidoc/asciidoc-py3
  license: GPL-2.0-only
  license_file: LICENSE
  summary: AsciiDoc is a text document format for writing things.
  description: >
    AsciiDoc is a text document format for writing notes, documentation,
    articles, books, ebooks, slideshows, web pages, man pages and blogs.
    AsciiDoc files can be translated to many formats including HTML, PDF, EPUB,
    man page.

    AsciiDoc is highly configurable: both the AsciiDoc source file syntax and
    the backend output markups (which can be almost any type of SGML/XML markup)
     can be customized and extended by the user.

extra:
  recipe-maintainers:
    - carlodri
