{% set name = "asciidoc" %}
{% set version = "10.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-py/{{ name }}-py/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8e1fb9691952cc4f13357e1ef58172e566c5f88e3c44222d4a8693585f884507

build:
  noarch: python
  entry_points:
    - asciidoc=asciidoc.asciidoc:cli
    - a2x=asciidoc.a2x:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - doc/asciidoc.txt
    - tests/**
  imports:
    - asciidoc
  commands:
    - pip check
    - asciidoc --help
    - a2x --help
    - asciidoc doc/asciidoc.txt
    - python3 tests/testasciidoc.py update && python3 tests/testasciidoc.py run || true
  requires:
    - pip

about:
  home: https://asciidoc.org
  doc_url: http://asciidoc.org/userguide.html
  dev_url: https://github.com/asciidoc/asciidoc-py3
  license: GPL-2.0-only
  license_file: LICENSE
  summary: AsciiDoc is a text document format for writing things.
  description: >
    AsciiDoc is a text document format for writing notes, documentation,
    articles, books, ebooks, slideshows, web pages, man pages and blogs.
    AsciiDoc files can be translated to many formats including HTML, PDF, EPUB,
    man page.

    AsciiDoc is highly configurable: both the AsciiDoc source file syntax and
    the backend output markups (which can be almost any type of SGML/XML markup)
     can be customized and extended by the user.

extra:
  recipe-maintainers:
    - carlodri
